name: Build Astroworld Installer

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    # Explicitly pin to Windows Server 2022 (instead of windows-latest)
    runs-on: windows-2022

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Build EXE with PyInstaller
        run: |
          pip install pyinstaller
          pyinstaller --onefile --windowed --icon=assets/app.ico main.py --name Astroworld

      - name: Clean previous build folder
        shell: cmd
        run: |
          if exist build rmdir /s /q build

      # 6️⃣ Upload MSI Artifact
      - name: Upload MSI Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Astroworld-MSI
          path: Astroworld.msi

      # 7️⃣ Upload EXE Artifact
      - name: Upload EXE Artifact
        uses: actions/upload-artifact@v4
        with:
          name: Astroworld-EXE
          path: application/Astroworld.exe

